title: Analyse de l’expression differentielle de genes a partir de donnees RNA- Seq (M2, année 2024-2025)
description: Apprendre à explorer des données de RNA-seq sur R
show_downloads: true
theme: jekyll-theme-modernist